# Generated by Django 4.2.4 on 2023-08-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='Not Avaialable', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
